version: '3.9'
services:
  mautic-database:
    image: mysql:8.0
    container_name: mautic-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - database
    volumes:
      - ./.storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}

  mautic:
    image: mautic/mautic:v4
    container_name: mautic
    restart: always
    depends_on:
      - mautic-database
    ports:
      - ${APP_PORT}:80
    networks:
      - default
    volumes:
      - ./.storage/mautic:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mautic-database
      - MAUTIC_DB_USER=${DB_USER}
      - MAUTIC_DB_PASSWORD=${DB_PASS}
      - MAUTIC_DB_NAME=${DB_NAME}
      - MAUTIC_RUN_CRON_JOBS=true

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - ${MAIL_PORT}:8025
    networks:
      - default

networks:
  default:
    name: docker_mautic_network
    driver: bridge

volumes:
  data:
    name: docker_mautic_data
    driver: local
